blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/Fe3mPqwxyn
    about: For general support, chat, and quick questions, reach us on Discord.
  - name: Email
    url: mailto:info@sndwrks.xyz
    about: Prefer email? Get in touch at info@sndwrks.xyz.
